// Generated by CoffeeScript 1.10.0
(function() {
  var app, cheerio, express, fs, path, request;

  express = require('express');

  path = require('path');

  fs = require('fs');

  request = require('request');

  cheerio = require('cheerio');

  app = express();

  app.get('/', function(req, res) {
    res.sendFile(path.join(__dirname + '/index.html'));
  });

  app.get('/team_api', function(req, res) {
    res.sendFile(path.join(__dirname + '/api.json'));
  });

  app.use('/css', express["static"](__dirname + '/css'));

  app.use('/js', express["static"](__dirname + '/js'));

  app.use('/images', express["static"](__dirname + '/images'));

  app.use('/bower_components', express["static"](__dirname + '/bower_components'));

  app.use('/node_modules', express["static"](__dirname + '/node_modules'));

  app.listen(3000);

  console.log('Running at Port 3000');

}).call(this);
